# Generated by Django 4.2.3 on 2023-09-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover",
            field=models.ImageField(blank=True, upload_to="covers/"),
        ),
    ]
